### ISSUE TITLE
Stale-While-Revalidate

### ISSUE THREAD

**Issue by wereHamster** [sozialhelden/fetch-cache#6]
Is it possible to implement something like Stale-While-Revalidate behaviour with fetch-cache? I'd like the cache to return the response immediately (if available in the cache), but then also send a request in the background to refresh the cache.

**Comment by opyh** [comment]
I guess something like this should work:

```
const response = fetchCache.cache.peek(url) || fetchCache.fetch(url, fetchOptions);
```

Feel free to reopen if this doesn't answer your question :)
